# Generated by Django 4.2.24 on 2025-10-06 23:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_remove_book_average_rating_bookrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrating',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='bookrating',
            unique_together={('user', 'book')},
        ),
    ]
