# Generated by Django 4.2.24 on 2025-10-02 15:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('book_description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('average_rating', models.FloatField()),
                ('cover_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('cover_image_alt', models.CharField(max_length=150)),
            ],
        ),
    ]
